[all]
all = """
all
Show all options.
"""

[action]
url = """
<url>
Add given <url> to subscription list (prefix http. Default).
"""
add = """
add <url> <title>
Add given <url> to subscription list (no feed validity check). Parameter <title> is optional.
"""
next = """
next <number>
Send next <number> of updates.
"""

[backup]
opml = """
export opml
Send an OPML file with feeds.
"""
md = """
export md
Send a Markdown file with feeds.
"""
# html = """
# backup news html
# Send an HTML formatted file of your news items.
# """
# md = """
# backup news md
# Send a Markdown file of your news items.
# """
# text = """
# backup news text
# Send a Plain Text file of your news items.
# """

[bookmarks]
bookmark = """
bookmark [+|-] <muc>
Groupchat to add or remove.
'+' appends to, '-' removes from.
"""
bookmarks = """
bookmarks
List bookmarked groupchats.
"""

[custom]
new = """
new
Send only new items of newly added feeds.
"""
old = """
old
Send all items of newly added feeds.
"""

[filters]
allow = """
allow [+|-] <keyword>
Keywords to allow
comma-separated keywords
'+' appends to, '-' removes from.
"""
deny = """
deny [+|-] <keyword>
Keywords to block
comma-separated keywords
'+' appends to, '-' removes from.
"""
clear_allow = """
clear allow
Reset allow list.
"""
clear_deny = """
clear deny
Reset deny list.
"""

[groupchat]
uri = """
<muc>
Join groupchat by given <muc> (prefix xmpp).
"""
join = """
join <muc>
Join groupchat by given <muc>.
"""
leave = """
goodbye
Leave groupchat and delete it from bookmarks.
"""

[manual]
all = """
help all
Print a complete list of commands.
"""
help = """
help
Print list of command types.
"""
command = """
help key command
Print command usage and description.
"""
info = """
info
Print information page.
"""
key = """
help <key>
Print list of commands for selected command type.
"""

# [mastership]
# demaster = """
# demaster <nick>
# Remove master privilege from given <nick>.
# """
# mastership = """
# mastership <nick>
# Add master privilege to given <nick>.
# """
# ownership = """
# ownership <nick>
# Transfer ownership to given <nick>.
# """

[message]
interval = """
interval <minutes>
Set interval update to every given <minutes>.
"""
length = """
length <number>
Set maximum length of news item description. (0 for no limit)
"""
media = """
media [off|on]
Attach media (i.e. audio, image, video) to messages when available.
"""
quantum = """
quantum <number>
Set amount of updates per message by given <number>.
"""
random = """
random [off|on]
Send messages by random order instead of date.
"""

[modification]
archive = """
archive <number>
Number of news items to archive (maximum value 500).
"""
default = """
default
Restore default settings.
"""
disable = """
disable <id>
Disable updates for feed of given <id>.
"""
enable = """
enable <id>
Enable updates for feed of given <id>.
"""
rename = """
rename <id> <name>
Rename feed of given <id> with new <name>.
"""
remove = """
remove <id>
Remove feed of from subscription list by given <id>.
"""
reset = """
reset
Mark all entries as read and remove all archived entries
"""
reset_url = """
reset <url>
Mark entries of given <url> as read and remove all its archived entries.
"""
start = """
start
Enable bot and send updates.
"""
stop = """
stop
Disable bot and stop updates.
"""

[options]
options = """
options
List options.
"""

[preview]
read = """
read <url>
Display recent 5 titles of given <url>.
"""
read_num = """
read <url> <index>
Display specified entry number from given <url> by given <index>.
"""

[pubsub]
pubsub = """
pubsub [off|on]
Designate JID as PubSub service.
"""

[send]
send = """
send <pubsub>/<jid> <url> <node>
Send feeds to given JID.
"""

[search]
feeds = """
feeds
List all subscriptions.
"""
feeds_keyword = """
feeds <text>
Search subscriptions by given <text>.
"""
search = """
search <text>
Search news items by given <text>.
"""
recent = """
recent <number>
List recent <number> news items (max. 50).
"""

[statistics]
stats = """
stats
Show general statistics.
"""
# analyses = """
# analyses
# Show report and statistics of feeds.
# """
# obsolete = """
# obsolete
# List feeds that are not available.
# """
# unread = """
# unread
# Print number of unread news items.
# """

# [token]
# activate = """
# activate <code>
# Activate given token to command bot by given <code>.
# """
