[about]
info = """
Slixfeed is a news broker bot for syndicated news which aims to be \
an easy to use and fully-featured news aggregating bot.

Slixfeed provides a convenient access to Blogs, News websites and \
even Fediverse instances, along with filtering and other privacy \
driven functionalities.

Slixfeed is designed primarily for the XMPP communication network \
(aka Jabber).

https://gitgud.io/sjehuda/slixfeed
"""

[note]
note = """
You can run your own Slixfeed instance as a client, from your own \
computer, server, and even from a Linux phone (i.e. Droidian, Kupfer, \
Mobian, NixOS, postmarketOS), as well as from Termux.

All you need is one of the above and an XMPP account to connect \
Slixfeed with.

Good luck!
"""

[authors]
info = """
Schimon Zackary
Laura Lapina
"""

[contributors]
info = """
Guus der Kinderen
grym (from #python IRC channel)
Stephen Paul Weber
"""

[bots]
info = """
Syndication bots made by our counterparts.

Morbot
https://codeberg.org/TheCoffeMaker/Morbot

feed-to-muc
https://salsa.debian.org/mdosch/feed-to-muc

JabRSS
http://www.jotwewe.de/de/xmpp/jabrss/jabrss_en.htm

JabRSS
https://dev.cmeerw.org/Projects/jabrss

err-rssreader"
https://github.com/errbotters/err-rssreader

XMPP Bot
https://github.com/nioc/xmpp-bot
"""

[legal]
info = """
Slixfeed is free software; you can redistribute it and/or modify it under the \
terms of the MIT License.

Slixfeed is distributed in the hope that it will be useful, but WITHOUT ANY \
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR \
A PARTICULAR PURPOSE.  See the MIT License for more details.

https://gitgud.io/sjehuda/slixfeed
"""

[license]
info = """
Copyright 2022 - 2024 Schimon Jehudah Zackary

Permission is hereby granted, free of charge, to any person obtaining a copy \
of this software and associated documentation files (the “Software”), to deal \
in the Software without restriction, including without limitation the rights \
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell \
copies of the Software, and to permit persons to whom the Software is \
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in \
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR \
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, \
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE \
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER \
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING \
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS \
IN THE SOFTWARE.
"""

[support]
info = """
Slixfeed Support Groupchat
xmpp:slixfeed@chat.woodpeckersnest.space?join
"""

[thanks]
info = """
From SalixOS to Gajim. A journey of 15 years. \
The people who have made all this possible.

Alixander Court (Utah), Arne-Brün Vogelsang (Germany), Chris Farrell (Oregon) \
Christian Dersch, Cyrille Pontvieux (France), Denis Fomin (Russia), Dimitris \
Tzemos (Greece), Emmanuel Gil Peyrot (France), Florent Le Coz (France), George \
Vlahavas (Greece), Guus der Kinderen (Netherlands), habnabit_ (#python), Imar \
van Erven Dorens (Netherlands), imattau (atomtopubsub), Jaussoin Timothée \
(France), Justin Karneges (California), Kevin Smith (Wales), Lars Windolf \
(Germany), Luis Henrique Mello (Brazil), magicfelix, Markus Muttilainen \
(SalixOS), Martin (Germany), Mathieu Pasquet (France), Maxime Buquet (France), \
mirux (Germany), Phillip Watkins (England), Pierrick Le Brun (France), Raphael \
Groner (Germany), Remko Tronçon (Belgium), Richard Lapointe (Connecticut), \
Simone "roughnecks" Canaletti (Italy), Strix from Loqi, Thibaud Guerin \
(SalixOS), Thorsten Fröhlich (France), Thorsten Mühlfelder (Germany), Tim \
Beech (Brazil), Tomoki Tsuchiya (SalixOS), Yann Leboulanger (France)

Thanks also to the friends of #python at irc.libera.chat
"""

[operators]
info = """
No operator was specified for this instance.
"""

[terms]
info = """
You are bound to these terms.
"""

[privacy]
info = """
All your data belongs to us.
"""

[clients]
info = """
Recommended Clients:

Cheogram
https://cheogram.com

Converse
https://conversejs.org

Gajim
https://gajim.org

monocles chat
https://monocles.chat

Movim
https://mov.im

Poezio
https://poez.io
"""

[services]
info = """
Recommended Syndication Services

Feed Creator
https://www.fivefilters.org/feed-creator/"

Kill the Newsletter
https://kill-the-newsletter.com

Open RSS
https://openrss.org

RSS-Bridge
https://rss-bridge.org/bridge01/

RSSHub
https://docs.rsshub.app
"""

[software]
info = """
Recommended News Software

CommaFeed
https://commafeed.com

FreshRSS
https://freshrss.org

Liferea
https://lzone.de/liferea/

NetNewsWire
https://netnewswire.com

Newsboat
https://newsboat.org

Spot-On
https://textbrowser.github.io/spot-on/

Vienna RSS
https://vienna-rss.com
"""

[resources]
info = """
Useful Resources:

feedparser
https://pythonhosted.org/feedparser

Slixmpp
https://slixmpp.readthedocs.io

XMPP
https://xmpp.org/about
"""

[rss-task-force]
info = """
The RSS Task Force (previously known as The Syndication Society) is an \
international organization headquartered in Switzerland.

It was originally formed to maintain, serve and improve data flow to and \
from small and medium enterprises, namely rural farms and long distance \
taxi drivers from Austria, Germany, Italy and Switzerland.

Thanks to a joint effort of transport and travel companies, in 2021 we have \
expanded our cause towards all entities of all types and sorts.

The RSS Task Force was founded by two taxicab drivers in 2018.
"""

[sleekxmpp]
info = """
SleekXMPP is an MIT licensed XMPP library for Python 2.6/3.1+, and is \
featured in examples in the book XMPP: The Definitive Guide by Kevin Smith, \
Remko Tronçon, and Peter Saint-Andre.

https://codeberg.org/fritzy/SleekXMPP
"""

[slixmpp]
info = """
Slixmpp is an MIT licensed XMPP library for Python 3.7+. It is a fork of \
SleekXMPP.

Slixmpp's goals is to only rewrite the core of the SleekXMPP library \
(the low level socket handling, the timers, the events dispatching) \
in order to remove all threads.

https://codeberg.org/poezio/slixmpp
"""

[xmpp]
info = """
XMPP is the Extensible Messaging and Presence Protocol, a set of open \
technologies for instant messaging, presence, multi-party chat, voice and \
video calls, collaboration, lightweight middleware, content syndication, and \
generalized routing of XML data.

https://xmpp.org/about
"""
